server:
  port: 6777
spring:
  datasource:
    druid:
      username: root
      password: xxx
      url: jdbc:mysql://mysql:3306/cool
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10                # 初始连接数，适当增加以缩短初始响应时间
      max-active: 200                 # 最大连接数，增大以支持更高并发访问
      min-idle: 10                    # 最小空闲连接数，保持一定数量的空闲连接以提高响应速度
      max-wait: 30000                 # 获取连接等待超时时间，设置为 30 秒，防止等待时间过长
      time-between-eviction-runs-millis: 30000  # 检测空闲连接的间隔时间，减少不必要的资源浪费
      min-evictable-idle-time-millis: 180000    # 最小空闲时间，设置为 3 分钟，及时释放不必要的连接
      validation-query: SELECT 1     # 测试 SQL，用于检测连接是否正常
      test-while-idle: true          # 是否在空闲时检查连接，保持默认
      test-on-borrow: true           # 获取连接时测试，保证获取到的连接是可用的
      test-on-return: false          # 归还连接时不测试，减少资源开销
      pool-prepared-statements: true # 是否打开 PSCache
      max-pool-prepared-statement-per-connection-size: 100  # 增大 PSCache 大小，提升性能
      stat-view-servlet:
        enabled: true                # 数据库监控端，不开请改false，开请设置下面的登录密码
        url-pattern: /druid/*
        allow: ""
        deny: ""
        login-username: 123456       # Web监控页面登录用户名，自己改
        login-password: 123456       # Web监控页面登录密码，自己改
        reset-enable: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          config:
            multi-statement-allow: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  web:
    resources:
      static-locations: classpath:/static/,file:upload/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

aliyun:
#  支付宝当面付接口
  alipay:
    gatewayUrl: https://openapi.alipay.com/gateway.do
    charset: UTF-8
    format: json
    signType: RSA2
#   ip请求限制
rate-limiter:
#   通常情况下
  capacity: 100
#  突发情况下
  refill-tokens: 200
#  间隔
  refill-duration: 1

fuclaude:
  # fuclaude获取登录链接的地址
  url: https://claude.pw
  auth-url: /manage-api/auth/oauth_token
  password: xxx

ip-auth:
  license: #授权码
